;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagRedirects=(OldTagName="GameplayCue.Skill1.Execute.DirectionPreview",NewTagName="GameplayCue.Skill1.DirectionPreview")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Buff.test",DevComment="테스트용 버프")
+GameplayTagList=(Tag="Data.Cooldown",DevComment="")
+GameplayTagList=(Tag="Data.Cooldown.Skill1",DevComment="")
+GameplayTagList=(Tag="Data.SkillID",DevComment="Skill_ID for skill")
+GameplayTagList=(Tag="Event.GA.Finished",DevComment="GA Finish Notify Event Tag From BT Task")
+GameplayTagList=(Tag="GameplayCue.Duration",DevComment="GC의 지속 적용을 위한 GE 입니다.")
+GameplayTagList=(Tag="GameplayCue.Effect.Projectile",DevComment="Projectile용 이펙트")
+GameplayTagList=(Tag="GameplayCue.Skill1.Actor",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Skill1.AreaPreview",DevComment="범위 지면 예시 이펙트 입니다")
+GameplayTagList=(Tag="GameplayCue.Skill1.DirectionPreview",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Skill1.Execute",DevComment="")
+GameplayTagList=(Tag="Move",DevComment="")
+GameplayTagList=(Tag="Skill.Skill1",DevComment="")
+GameplayTagList=(Tag="Skill.Skill2",DevComment="")
+GameplayTagList=(Tag="Skill.Skill3",DevComment="")
+GameplayTagList=(Tag="Skill.Skill4",DevComment="")
+GameplayTagList=(Tag="Skill.Skill5",DevComment="")
+GameplayTagList=(Tag="Skill.Skill6",DevComment="")
+GameplayTagList=(Tag="Skill.Skill7",DevComment="")
+GameplayTagList=(Tag="Skill.Skill8",DevComment="")
+GameplayTagList=(Tag="Skill.TargetLocation",DevComment="")

