;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagRedirects=(OldTagName="GameplayCue.Skill1.Execute.DirectionPreview",NewTagName="GameplayCue.Skill1.DirectionPreview")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Buff.test",DevComment="테스트용 버프")
+GameplayTagList=(Tag="Data.Cooldown.Skill1",DevComment="스킬1의 쿨다운 데이터")
+GameplayTagList=(Tag="Data.SkillID",DevComment="스킬 식별자 데이터")
+GameplayTagList=(Tag="GameplayCue.Duration",DevComment="GC의 지속 적용을 위한 GE 입니다")
+GameplayTagList=(Tag="GameplayCue.Effect.Projectile",DevComment="발사체용 이펙트")
+GameplayTagList=(Tag="GameplayCue.Skill1.Actor",DevComment="스킬1 액터 관련 이펙트")
+GameplayTagList=(Tag="GameplayCue.Skill1.AreaPreview",DevComment="범위 지면 예시 이펙트")
+GameplayTagList=(Tag="GameplayCue.Skill1.DirectionPreview",DevComment="방향성 스킬 프리뷰 이펙트")
+GameplayTagList=(Tag="GameplayCue.Skill1.Execute",DevComment="스킬1 실행 이펙트")
+GameplayTagList=(Tag="Move",DevComment="이동 관련 태그")
+GameplayTagList=(Tag="Skill.Skill1",DevComment="1번 스킬")
+GameplayTagList=(Tag="Skill.Skill2",DevComment="2번 스킬")
+GameplayTagList=(Tag="Skill.Skill3",DevComment="3번 스킬")
+GameplayTagList=(Tag="Skill.Skill4",DevComment="4번 스킬")
+GameplayTagList=(Tag="Skill.Skill5",DevComment="5번 스킬")
+GameplayTagList=(Tag="Skill.Skill6",DevComment="6번 스킬")
+GameplayTagList=(Tag="Skill.Skill7",DevComment="7번 스킬")
+GameplayTagList=(Tag="Skill.Skill8",DevComment="8번 스킬")
+GameplayTagList=(Tag="State.Player.Idle",DevComment="플레이어가 대기 상태일 때의 상태")
+GameplayTagList=(Tag="State.Player.Combat",DevComment="플레이어가 전투 상태일 때의 상태")
+GameplayTagList=(Tag="State.Player.Stunned",DevComment="플레이어가 기절 상태일 때의 상태")
+GameplayTagList=(Tag="State.Player.Knockback",DevComment="플레이어가 넉백 상태일 때의 상태")
+GameplayTagList=(Tag="State.Player.Dead",DevComment="플레이어가 사망 상태일 때의 상태")
+GameplayTagList=(Tag="State.Player.Hit",DevComment="플레이어가 피격 상태일 때의 상태")
+GameplayTagList=(Tag="Cue.None",DevComment="기본 Cue 상태")
+GameplayTagList=(Tag="Cue.DirectionPreview",DevComment="방향성 스킬 프리뷰")
+GameplayTagList=(Tag="Cue.AreaAttackWarning",DevComment="범위 공격 경고")
+GameplayTagList=(Tag="GasEvent.None",DevComment="기본 GAS 이벤트 상태")
+GameplayTagList=(Tag="GasEvent.AbilityFinished",DevComment="어빌리티 종료 이벤트")
+GameplayTagList=(Tag="Skill",DevComment="스킬 시스템의 기본 태그")
+GameplayTagList=(Tag="Skill.Attack",DevComment="기본 공격")
+GameplayTagList=(Tag="Skill.Skill9",DevComment="9번 스킬")
+GameplayTagList=(Tag="Data.None",DevComment="기본 데이터 상태")
+GameplayTagList=(Tag="Data.Cooldown",DevComment="쿨다운 데이터")

